correct check

diff --git a/.github/workflows/docker_image_deploy.yml b/.github/workflows/docker_image_deploy.yml
--- a/.github/workflows/docker_image_deploy.yml
+++ b/.github/workflows/docker_image_deploy.yml
@@ -17,7 +17,7 @@ jobs:
         SECRET_DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
         SECRET_DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
       run: |
-        [ -z "$SECRET_DOCKERHUB_PASSWORD"]
+        if [[ -z "$SECRET_DOCKERHUB_PASSWORD"]]; then echo "Missing variable SECRET_DOCKERHUB_PASSWORD" && exit 1; fi
     - name: Check variables
       env:
         EVENT_NAME: ${{ github.event_name }}
